"""Initial schema with city_code

Revision ID: aaec4e68d042
Revises: 
Create Date: 2026-06-07 13:27:04.377707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaec4e68d042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('stops', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('delete_indicator', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flights_dest', 'flights', ['destination', 'delete_indicator'], unique=False)
    op.create_index('idx_flights_full_search', 'flights', ['origin', 'destination', 'departure_date', 'return_date'], unique=False)
    op.create_index('idx_flights_search', 'flights', ['origin', 'departure_date', 'price'], unique=False, postgresql_where=sa.text('delete_indicator = 0'))
    op.create_table('scraper_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_soft_deleted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_logs')
    op.drop_index('idx_flights_search', table_name='flights', postgresql_where=sa.text('delete_indicator = 0'))
    op.drop_index('idx_flights_full_search', table_name='flights')
    op.drop_index('idx_flights_dest', table_name='flights')
    op.drop_table('flights')
    op.drop_table('airports')
    # ### end Alembic commands ###
